from pathlib import Path
import re

path = Path('index.html')
text = path.read_text(encoding='utf-8')

text = re.sub(r'<title>.*?</title>', '<title>딱이것만 | AI 요청 최적화 · 사진 복원 · 영상화</title>', text, count=1, flags=re.S)

CSS = r'''/* HOME_REDESIGN_START */
:root{--cream:#fbfaf6;--deep:#071b3b;--deep2:#0d2a57;--gold:#e8b84f;--goldsoft:#fff3d5;--softline:#ebe7dc;--home-muted:#6c7481}
body{background:radial-gradient(circle at 9% 0%,rgba(255,232,178,.28),transparent 24%),radial-gradient(circle at 93% 7%,rgba(220,230,255,.25),transparent 22%),var(--cream)}
.app{max-width:1080px}
.topbar{position:sticky;top:0;z-index:60;margin:-20px -2px 0;padding:14px 2px 12px;background:rgba(251,250,246,.9);backdrop-filter:blur(16px);border-bottom:1px solid rgba(232,227,215,.72)}
.brand-new{display:flex;align-items:center;gap:11px;border:0;background:transparent;padding:0;cursor:pointer;text-align:left}.brand-mark{width:44px;height:44px;border-radius:14px;background:radial-gradient(circle at 24% 18%,rgba(255,255,255,.22),transparent 23%),linear-gradient(145deg,#06172f,#0b2b61);box-shadow:0 9px 24px rgba(7,27,59,.16);display:grid;place-items:center;color:#f3c65e;font-size:22px;position:relative}.brand-mark:after{content:'✧';position:absolute;right:7px;top:4px;font-size:12px;color:#fff4cd}.brand-new strong{display:block;color:var(--deep);font-size:22px;letter-spacing:-.6px}.brand-new small{display:block;margin-top:3px;color:#727b89;font-size:11px;font-weight:700}.topbar .nav .nav-cta{background:var(--deep);color:#fff}.hamb{display:none;width:44px;height:44px;border:1px solid var(--softline);background:#fffefa;border-radius:14px;align-items:center;justify-content:center;flex-direction:column;gap:4px}.hamb i{width:19px;height:2px;border-radius:99px;background:var(--deep)}
.mobile-menu{display:none;position:fixed;inset:0;z-index:120;background:rgba(7,27,59,.28);backdrop-filter:blur(6px);padding:18px}.mobile-menu.show{display:flex;justify-content:flex-end;align-items:flex-start}.mobile-sheet{width:min(330px,92vw);background:#fffefa;border:1px solid var(--softline);border-radius:24px;padding:22px;box-shadow:0 22px 60px rgba(7,27,59,.2)}.mobile-sheet h3{margin:0;color:var(--deep);font-size:24px}.mobile-sheet p{margin:6px 0 16px;color:var(--home-muted);font-size:12px}.mobile-sheet button{width:100%;border:0;background:#f6f4ee;color:var(--deep);padding:13px 14px;border-radius:13px;margin-top:8px;text-align:left;font-weight:900}.mobile-sheet .m-primary{background:var(--deep);color:#fff}.m-close{float:right!important;width:34px!important;height:34px!important;padding:0!important;margin:0!important;border-radius:50%!important;text-align:center!important;font-size:21px!important}
#home{padding-top:0}.home-hero-new{text-align:center;position:relative;padding:70px 10px 34px;overflow:hidden}.home-hero-new:before{content:'';position:absolute;width:520px;height:520px;left:50%;top:-300px;transform:translateX(-50%);background:radial-gradient(circle,rgba(249,214,132,.28),transparent 68%)}.home-eyebrow{position:relative;display:inline-flex;align-items:center;gap:6px;padding:8px 12px;border-radius:999px;background:rgba(255,253,247,.8);border:1px solid #f0e3c4;color:#8b6820;font-size:11px;font-weight:900}.home-eyebrow:before{content:'✦';color:var(--gold)}.home-hero-new h1{position:relative;margin:18px 0 0;color:var(--deep);font-size:clamp(47px,7vw,78px);line-height:1.02;letter-spacing:-3.4px}.home-hero-new h1 em{font-style:normal;color:var(--gold)}.home-hero-new p{position:relative;margin:17px 0 0;color:#4e5968;font-size:clamp(16px,2vw,22px)}.home-hero-line{width:86px;height:4px;border-radius:99px;background:linear-gradient(90deg,transparent,var(--gold),transparent);margin:10px auto 0;transform:rotate(-3deg)}.spark-a,.spark-b,.spark-c{position:absolute;color:#efc45e}.spark-a{left:13%;top:58%}.spark-b{right:14%;top:45%;font-size:22px}.spark-c{right:7%;top:68%;font-size:12px}
.quick-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:17px}.quick-card{min-height:292px;border:1px solid var(--softline);border-radius:26px;background:rgba(255,255,255,.86);padding:18px 14px 54px;text-align:center;cursor:pointer;box-shadow:0 12px 30px rgba(31,41,55,.06);position:relative;transition:.17s}.quick-card:hover{transform:translateY(-3px);box-shadow:0 18px 38px rgba(31,41,55,.09)}.quick-card.primary-card{background:linear-gradient(180deg,var(--deep) 0 36%,rgba(255,255,255,.96) 36%)}.quick-card.gold-card{background:linear-gradient(180deg,#fffef9,#fff8e7);border-color:#eeddae}.quick-icon{width:72px;height:72px;border-radius:50%;display:grid;place-items:center;margin:4px auto 16px;color:#fff;font-size:27px;font-weight:950;box-shadow:0 9px 20px rgba(24,37,58,.13);position:relative}.quick-icon:after{content:'✦';position:absolute;right:5px;top:2px;font-size:13px;color:#fff5cf}.qi-ai{background:linear-gradient(145deg,#214d95,#0b2857)}.qi-photo{background:linear-gradient(145deg,#6fa8dc,#24578e)}.qi-video{background:linear-gradient(145deg,#947ae0,#4f3fa5)}.qi-gold{background:linear-gradient(145deg,#f7d779,#dda93a);color:#fff5cf}.qi-gold:after{display:none}.quick-card strong{display:block;min-height:50px;color:var(--deep);font-size:20px;line-height:1.2;letter-spacing:-.5px}.quick-card small{display:block;color:#68717f;font-size:12px;line-height:1.5}.quick-arrow{position:absolute;bottom:17px;left:50%;transform:translateX(-50%);width:46px;height:33px;border-radius:999px;background:var(--deep);color:#fff;display:grid;place-items:center;font-size:18px}.gold-card .quick-arrow{background:var(--gold)}
.home-benefits{display:grid;grid-template-columns:repeat(3,1fr);background:rgba(255,255,255,.8);border:1px solid var(--softline);border-radius:22px;padding:16px 18px;margin-bottom:26px;box-shadow:0 8px 24px rgba(24,37,58,.04)}.home-benefit{display:flex;align-items:center;justify-content:center;gap:12px;padding:2px 16px;border-left:1px solid #ece8df}.home-benefit:first-child{border-left:0}.home-benefit b{width:40px;height:40px;border-radius:50%;background:var(--deep);color:#fff;display:grid;place-items:center;font-size:18px}.home-benefit strong{display:block;font-size:13px;color:var(--deep)}.home-benefit small{display:block;color:#7c8490;font-size:10px;margin-top:3px}
.restore-new{display:grid;grid-template-columns:.72fr 1.28fr;gap:18px;background:rgba(255,255,255,.86);border:1px solid var(--softline);border-radius:29px;padding:17px;box-shadow:0 14px 36px rgba(24,37,58,.06)}.restore-copy-new{padding:16px 8px;display:flex;flex-direction:column;justify-content:center}.soft-pill{align-self:flex-start;padding:7px 11px;border-radius:999px;background:var(--goldsoft);color:#9a7122;font-size:10px;font-weight:900}.restore-copy-new h2{margin:15px 0 13px;color:var(--deep);font-size:31px;line-height:1.24;letter-spacing:-1px}.restore-copy-new h2 span{color:var(--gold)}.restore-bullets{display:grid;gap:8px}.restore-bullets div{border:1px solid #ece8df;background:#fff;border-radius:11px;padding:9px 11px;color:#667085;font-size:11px}.restore-copy-new button{align-self:flex-start;border:0;background:transparent;color:#9a7122;font-weight:900;padding:13px 0 0;cursor:pointer}.restore-visual{display:grid;grid-template-columns:1fr 1fr;position:relative;overflow:hidden;border-radius:21px;min-height:260px;background:#d6d0c7}.portrait-half{position:relative;display:flex;align-items:flex-end;justify-content:center;overflow:hidden}.portrait-half:before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 33%,#c4a987 0 9%,transparent 10%),radial-gradient(ellipse at 50% 72%,#6b5140 0 25%,transparent 26%),linear-gradient(150deg,#bbb2a6,#756d63)}.portrait-half.before:after{content:'';position:absolute;inset:0;background:repeating-linear-gradient(72deg,transparent 0 34px,rgba(255,255,255,.25) 35px 36px,transparent 37px 55px);mix-blend-mode:screen;opacity:.75;filter:grayscale(1)}.portrait-half.after:before{background:radial-gradient(circle at 50% 33%,#d6a57d 0 9%,transparent 10%),radial-gradient(ellipse at 50% 72%,#28394e 0 25%,transparent 26%),linear-gradient(145deg,#9bb5c5,#d8c0a3)}.portrait-half label{position:relative;z-index:2;margin-bottom:13px;padding:6px 9px;border-radius:999px;background:rgba(7,27,59,.74);color:#fff;font-size:9px;font-weight:900}.portrait-half.after label{background:rgba(244,207,117,.88);color:#5d3d09}.split-knob{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);z-index:4;width:44px;height:44px;border-radius:50%;display:grid;place-items:center;background:#fff;color:var(--deep);font-weight:950;box-shadow:0 5px 18px rgba(0,0,0,.14)}
.studio-new{margin-top:18px;min-height:250px;display:grid;grid-template-columns:.9fr 1.1fr;border-radius:29px;overflow:hidden;background:radial-gradient(circle at 72% 63%,rgba(234,184,79,.2),transparent 22%),linear-gradient(135deg,#071b3b,#0a254f 58%,#111928);color:#fff;box-shadow:0 18px 42px rgba(7,27,59,.14);cursor:pointer}.studio-copy-new{padding:29px 27px}.studio-copy-new .studio-title{font-size:24px;font-weight:950;color:#f2c761}.studio-copy-new h2{margin:9px 0 7px;font-size:29px;line-height:1.18;letter-spacing:-1px}.studio-copy-new p{margin:0;color:#c9d3e2;font-size:12px}.studio-pills{display:flex;gap:7px;flex-wrap:wrap;margin-top:22px}.studio-pills span{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.1);padding:8px 10px;border-radius:10px;font-size:10px;font-weight:850}.studio-art{position:relative;min-height:250px}.stage{position:absolute;width:170px;height:48px;border:3px solid rgba(237,190,82,.72);border-radius:50%;left:50%;bottom:38px;transform:translateX(-50%);box-shadow:0 0 38px rgba(237,190,82,.44),inset 0 0 22px rgba(237,190,82,.16)}.glass{position:absolute;border:1px solid rgba(255,255,255,.2);background:linear-gradient(145deg,rgba(255,255,255,.15),rgba(255,255,255,.04));backdrop-filter:blur(7px);border-radius:13px;display:grid;place-items:center;box-shadow:0 12px 27px rgba(0,0,0,.22)}.glass.main{width:102px;height:116px;left:50%;bottom:63px;transform:translateX(-50%);font-size:35px;font-weight:950;color:#fff1ce}.glass.one{width:68px;height:82px;left:17%;bottom:57px;color:#9dc7ff;font-size:23px}.glass.two{width:70px;height:84px;right:17%;bottom:57px;color:#c2b1f4;font-size:22px}.art-line{position:absolute;left:8%;right:8%;bottom:23px;height:2px;background:linear-gradient(90deg,transparent,rgba(237,190,82,.6),transparent)}
.home-cta-new{margin-top:18px;border:1px solid #eedcae;border-radius:27px;background:radial-gradient(circle at 93% 50%,rgba(238,190,79,.2),transparent 25%),linear-gradient(120deg,#fffef9,#fff8e9);display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:17px;padding:24px 26px}.cta-spark{font-size:38px;color:var(--gold)}.home-cta-new h2{margin:0;color:var(--deep);font-size:29px;letter-spacing:-.8px}.home-cta-new p{margin:4px 0 0;color:#707987;font-size:12px}.home-cta-new button{border:0;background:var(--deep);color:#f1c762;border-radius:999px;padding:16px 24px;font-weight:950;min-width:205px;cursor:pointer}.home-note{text-align:center;padding:22px 0 3px;color:#a0a6ae;font-size:10px}
@media(max-width:820px){.topbar .nav{display:none}.hamb{display:flex}.quick-grid{grid-template-columns:repeat(2,1fr)}.restore-new{grid-template-columns:1fr}.studio-new{grid-template-columns:1fr 1fr}}
@media(max-width:680px){.topbar{margin:-14px -2px 0;padding-top:10px}.brand-new strong{font-size:20px}.brand-new small{font-size:9.8px}.brand-mark{width:40px;height:40px}.home-hero-new{padding:49px 3px 27px}.home-hero-new h1{font-size:49px;letter-spacing:-3px}.home-hero-new p{font-size:16px}.quick-grid{gap:10px}.quick-card{min-height:240px;border-radius:21px;padding:14px 9px 48px}.quick-icon{width:60px;height:60px;font-size:23px;margin:3px auto 11px}.quick-card strong{font-size:17px;min-height:41px}.quick-card small{font-size:10.5px}.quick-arrow{bottom:12px;width:42px;height:30px}.home-benefits{grid-template-columns:1fr;padding:8px 13px}.home-benefit{justify-content:flex-start;border-left:0;border-top:1px solid #ece8df;padding:10px 3px}.home-benefit:first-child{border-top:0}.restore-new{padding:12px;border-radius:22px}.restore-copy-new{padding:11px 7px 2px}.restore-copy-new h2{font-size:25px}.restore-visual{min-height:210px;border-radius:17px}.studio-new{grid-template-columns:1fr;min-height:420px;border-radius:22px}.studio-copy-new{padding:23px 21px 0}.studio-copy-new h2{font-size:26px}.studio-art{min-height:205px}.home-cta-new{grid-template-columns:auto 1fr;padding:19px 17px;border-radius:21px}.home-cta-new button{grid-column:1/-1;width:100%;min-width:0}.home-cta-new h2{font-size:24px}.cta-spark{font-size:31px}}
/* HOME_REDESIGN_END */'''

text = re.sub(r'/\* HOME_REDESIGN_START \*/.*?/\* HOME_REDESIGN_END \*/', '', text, flags=re.S)
text = text.replace('</style>', CSS + '\n</style>', 1)

HEADER = r'''<header class="topbar">
  <button class="brand-new" onclick="goHome()" aria-label="홈으로">
    <span class="brand-mark">✦</span>
    <span><strong>딱이것만</strong><small>AI 요청 최적화 · 사진 복원 · 영상화</small></span>
  </button>
  <nav class="nav"><button onclick="goHome()">홈</button><button onclick="openPage('tools')">무료 도구</button><button onclick="openPage('studio')">AI 작업실</button><button class="nav-cta" onclick="openModule('create')">무료로 시작</button></nav>
  <button class="hamb" onclick="toggleHomeMenu()" aria-label="메뉴"><i></i><i></i><i></i></button>
</header>
<div id="homeMenu" class="mobile-menu" onclick="if(event.target===this)toggleHomeMenu(false)"><div class="mobile-sheet"><button class="m-close" onclick="toggleHomeMenu(false)">×</button><h3>딱이것만</h3><p>원하는 작업으로 바로 이동하세요.</p><button onclick="toggleHomeMenu(false);goHome()">홈</button><button onclick="toggleHomeMenu(false);openPage('tools')">무료 AI 도구</button><button onclick="toggleHomeMenu(false);openPage('studio')">AI 작업실</button><button class="m-primary" onclick="toggleHomeMenu(false);openModule('create')">무료 요청문 만들기</button></div></div>'''

text = re.sub(r'<header class="topbar">.*?</header>', HEADER, text, count=1, flags=re.S)

HOME = r'''<main id="home" class="page-screen active">
  <section class="home-hero-new"><span class="spark-a">✦</span><span class="spark-b">✧</span><span class="spark-c">✦</span><div class="home-eyebrow">AI를 어렵게 쓰지 않아도 돼요</div><h1>원하는 것만,<br><em>딱</em> 이것만</h1><p>초보자도 쉽게 AI 요청문 만들기</p><div class="home-hero-line"></div></section>
  <section class="quick-grid">
    <button class="quick-card primary-card" onclick="openModule('create')"><span class="quick-icon qi-ai">AI</span><strong>무료 요청문<br>만들기</strong><small>AI에 딱 맞는<br>요청문 자동 생성</small><span class="quick-arrow">→</span></button>
    <button class="quick-card" onclick="openPage('restore')"><span class="quick-icon qi-photo">▧</span><strong>사진 복원</strong><small>낡고 흐릿한 사진을<br>선명하게 복원</small><span class="quick-arrow">→</span></button>
    <button class="quick-card" onclick="openPage('animate')"><span class="quick-icon qi-video">▶</span><strong>복원 사진<br>영상화</strong><small>복원된 사진으로<br>짧은 영상 만들기</small><span class="quick-arrow">→</span></button>
    <button class="quick-card gold-card" onclick="openPage('studio')"><span class="quick-icon qi-gold">♛</span><strong>제작 의뢰</strong><small>필요한 작업을 골라<br>여기서 바로 진행</small><span class="quick-arrow">→</span></button>
  </section>
  <section class="home-benefits"><div class="home-benefit"><b>▯</b><span><strong>모바일 최적화</strong><small>언제 어디서나 간편하게</small></span></div><div class="home-benefit"><b>☺</b><span><strong>초보자 쉬움</strong><small>누구나 쉽게 사용</small></span></div><div class="home-benefit"><b>◇</b><span><strong>결과물 중심</strong><small>필요한 결과에 집중</small></span></div></section>
  <section class="restore-new"><div class="restore-copy-new"><span class="soft-pill">사진 복원 예시</span><h2>흐릿했던 추억,<br>선명하게 복원 <span>✦</span></h2><div class="restore-bullets"><div>☹ &nbsp; 낡고 흐린 사진</div><div>☺ &nbsp; 선명한 고화질 복원</div></div><button onclick="openPage('restore')">복원 서비스 보기 →</button></div><div class="restore-visual"><div class="portrait-half before"><label>복원 전</label></div><div class="portrait-half after"><label>복원 후</label></div><span class="split-knob">‹ ›</span></div></section>
  <section class="studio-new" onclick="openPage('studio')" role="button" tabindex="0"><div class="studio-copy-new"><div class="studio-title">✦ AI 작업실</div><h2>프롬프트가 아니라<br>결과가 필요할 때</h2><p>복원부터 업스케일, 영상화까지 한곳에서.</p><div class="studio-pills"><span>✦ 복원</span><span>HD 업스케일</span><span>▶ 영상화</span></div></div><div class="studio-art"><span class="stage"></span><span class="glass one">▧</span><span class="glass main">AI</span><span class="glass two">▶</span><span class="art-line"></span></div></section>
  <section class="home-cta-new"><span class="cta-spark">✦</span><div><h2>지금 시작하기</h2><p>딱 필요한 기능만, 딱 좋은 결과만</p></div><button onclick="openModule('create')">무료로 시작하기 &nbsp; →</button></section>
  <div class="home-note">딱이것만 · AI를 어렵게 쓰지 않는 방법</div>
</main>'''

text, n = re.subn(r'<main id="home" class="page-screen active">.*?</main>\s*(?=<section id="page-tools")', HOME + '\n', text, count=1, flags=re.S)
if n != 1:
    raise SystemExit('Could not find home section')

if 'function toggleHomeMenu(' not in text:
    hook = "const MODULE_NAMES=new Set"
    js = """function toggleHomeMenu(force){const el=document.getElementById('homeMenu');if(!el)return;const show=typeof force==='boolean'?force:!el.classList.contains('show');el.classList.toggle('show',show);document.body.style.overflow=show?'hidden':'';}\n"""
    text = text.replace(hook, js + hook, 1)

path.write_text(text, encoding='utf-8')
print('Homepage redesign applied')
